### ISSUE TITLE
Rewrite `page_processor.rb`

### ISSUE THREAD

**Issue by rpbaptist** [wolves-2014/hmhy#101]
I starting writing a parser object for creating a therapist for each line in the CSV file and then I realized something I wish we were told when we started building this: **Saving these things as CSV was a bad idea.**

This parser already identifies all the attributes for a `Therapist`. Instead of throwing these all in one line, we could already make attributes which we can directly translate to a Ruby object.
1. Instead of an array, build a hash with Nokogiri
2. Save the hash with `.to_yaml` to a file.

Now things become super simple!
1. Read in the YAML file
2. Loop through each record
3. Create a new `Therapist` with the recorded attributes
4. ...?
5. Profit!

**Comment by rpbaptist** [comment]
@RyanMilstead1 @luminous14 @schreuderjo Please let me know what you think, because I am starting on this now.

**Comment by rpbaptist** [comment]
I would be happy to pair on any of this.

**Comment by luminous14** [comment]
I would be too... I feel bad but I'm just too busy to do actual code
contributions to hmhy. I'm happy to look over pull requests though.
